version: '3'
services:
  web:
    container_name: lfi-to-rce
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9005:80
    volumes:
       - ./src/:/var/www/html/
    image: moeinfatehi/lfi-to-rce:latest